#!/bin/bash
if [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
   if [ "$TRAVIS_BRANCH" = 'master' ]; then
       openssl aes-256-cbc -K $encrypted_f5e90db9d6e7_key -iv $encrypted_f5e90db9d6e7_iv -in .travis/codesigning.asc.enc -out .travis/codesigning.asc -d
       gpg --fast-import .travis/codesigning.asc
   fi
fi
